[tasks.build]
description = "Build the protocol document"
dir = "protocol"
sources = ["BCH3_WS2025_Glycin_Titration.typ", "assets/**/*", "data/**/*"]
outputs = ["BCH3_WS2025_Glycin_Titration.pdf"]
run = "typst compile BCH3_WS2025_Glycin_Titration.typ"
