# yaml-language-server: $schema=https://raw.githubusercontent.com/mkdjr/hayagriva/refs/heads/main/hayagriva.schema.json

src_chlorophyll-a-photochem:
  type: web
  url: 
    value: https://www.photochemcad.com/databases/common-compounds/chlorins-bacteriochlorins/chlorophyll-a
    date: 2025-12-01
  title: PhotochemCAD | Chlorophyll a
  author:
  - Lindsey, Jonathan S.
  - Taniguchi, Masahiko
  - Du, Hai
  organization: North Carolina State University
  parent: 
    type: article
    title: Database of Absorption and Fluorescence Spectra of >300 Common Compounds for use in PhotochemCAD
    author:
    - Taniguchi, Masahiko
    - Lindsey, Jonathan S.
    date: 2018
    page-range: 290-327
    url: https://onlinelibrary.wiley.com/doi/abs/10.1111/php.12860
    serial-number:
      doi: https://doi.org/10.1111/php.12860
    abstract: Abstract The design of new molecules for photochemical studies typically requires knowledge of spectral features of pertinent chromophores beginning with the absorption spectrum (λabs) and accompanying molar absorption coefficient (ε, m−1 cm−1) and often extending to the fluorescence spectrum (λem) and fluorescence quantum yield (Φf), where the fluorescence properties may be of direct relevance or useful as proxies to gain insight into the nature of the first excited singlet state. PhotochemCAD databases, developed over a period of 30 years, are described here. The previous databases for 150 compounds have been expanded to encompass 339 compounds for which absorption spectra (including ε values), fluorescence spectra (including Φf values) and references to the primary literature have been included where available (552 spectra altogether). The compounds exhibit spectra in the ultraviolet, visible and/or near-infrared spectral regions. The compound classes and number of members include acridines (21), aromatic hydrocarbons (41), arylmethane dyes (11), azo dyes (18), biomolecules (18), chlorins/bacteriochlorins (16), coumarins (14), cyanine dyes (19), dipyrrins (7), heterocycles (26), miscellaneous dyes (13), oligophenylenes (13), oligopyrroles (6), perylenes (5), phthalocyanines (11), polycyclic aromatic hydrocarbons (16), polyenes/polyynes (10), porphyrins (34), quinones (24) and xanthenes (15). A database of 31 solar spectra also is included.
    parent:
      type: periodical
      title: Photochemistry and Photobiology
      issue: 2
      volume: 94

src_chlorophyll-b-photochem:
  type: web
  url: 
    value: https://www.photochemcad.com/databases/common-compounds/chlorins-bacteriochlorins/chlorophyll-b
    date: 2025-12-01
  title: PhotochemCAD | Chlorophyll b
  author:
  - Lindsey, Jonathan S.
  - Taniguchi, Masahiko
  - Du, Hai
  organization: North Carolina State University
  parent: 
    type: article
    title: Database of Absorption and Fluorescence Spectra of >300 Common Compounds for use in PhotochemCAD
    author:
    - Taniguchi, Masahiko
    - Lindsey, Jonathan S.
    date: 2018
    page-range: 290-327
    url: https://onlinelibrary.wiley.com/doi/abs/10.1111/php.12860
    serial-number:
      doi: https://doi.org/10.1111/php.12860
    abstract: Abstract The design of new molecules for photochemical studies typically requires knowledge of spectral features of pertinent chromophores beginning with the absorption spectrum (λabs) and accompanying molar absorption coefficient (ε, m−1 cm−1) and often extending to the fluorescence spectrum (λem) and fluorescence quantum yield (Φf), where the fluorescence properties may be of direct relevance or useful as proxies to gain insight into the nature of the first excited singlet state. PhotochemCAD databases, developed over a period of 30 years, are described here. The previous databases for 150 compounds have been expanded to encompass 339 compounds for which absorption spectra (including ε values), fluorescence spectra (including Φf values) and references to the primary literature have been included where available (552 spectra altogether). The compounds exhibit spectra in the ultraviolet, visible and/or near-infrared spectral regions. The compound classes and number of members include acridines (21), aromatic hydrocarbons (41), arylmethane dyes (11), azo dyes (18), biomolecules (18), chlorins/bacteriochlorins (16), coumarins (14), cyanine dyes (19), dipyrrins (7), heterocycles (26), miscellaneous dyes (13), oligophenylenes (13), oligopyrroles (6), perylenes (5), phthalocyanines (11), polycyclic aromatic hydrocarbons (16), polyenes/polyynes (10), porphyrins (34), quinones (24) and xanthenes (15). A database of 31 solar spectra also is included.
    parent:
      type: periodical
      title: Photochemistry and Photobiology
      issue: 2
      volume: 94

src_wikipedia-solvatochromism:
  type: web
  url: 
    value: https://en.wikipedia.org/wiki/Solvatochromism
    date: 2025-12-05
  title: Solvatochromism - Wikipedia
  organization: Wikipedia
  parent:
    type: article

src_chlorophyll-lichtenthaler:
  type: article
  title: Chlorophyll and Carotenoid Determination
  author: Lichtenthaler, Hartmut K.
  organization: Karlsruhe Institute of Technology (KIT)
  url:
    value: https://www.jkip.kit.edu/molbio/download/1A_Chlorophylls_Carotenoid_determin-HKLi_2010.pdf
    date: 2025-12-05

src_plants-in-action:
  type: book
  url:
    value: https://rseco.org/content/122-chlorophyll-absorption-and-photosynthetic-action-spectra.html
    date: 2025-12-06
  title: Plants in Action
  author:
  - Australian Society of Plant Scientists
  editor:
  - Munns, Rana
  - Schmidt, Susanne
  - Beveridge, Christine
  - Mathesius, Ulrike
  edition: 2
  chapter: 1.2.2
  language: en
  date: 2018

src_chlorophyll-extraction-protocol:
  type: report
  title: Chlorophyll Extraction and Determination
  author:
  - Hendrik Poorter
  - Yvonne de Jong-Van Berkel
  language: en
  url:
    value: https://prometheusprotocols.net/function/tissue-chemistry/pigments/chlorophyll-extraction-and-determination/
    date: 2025-12-09

src_quartz-cuvette:
  title: Quartz cuvette - Qvarz LLC
  type: web
  url:
    value: https://qvarz.com/quartz-cuvette/
    date: 2025-12-29
  organization: Qvarz LLC

src_wikipedia-molar-extinction-coefficient:
  type: web
  url:
    value: https://en.wikipedia.org/wiki/Molar_absorption_coefficient
    date: 2025-12-29
  title: Molar extinction coefficient - Wikipedia
  organization: Wikipedia
  parent:
    type: article

src_coeffecients:
  type: article
  title: Precise estimation of chlorophyll a, b and carotenoid content by deconvolution of the absorption spectrum and new simultaneous equations for Chl determination
  author:
  - Chazaux, Marie
  - Schiphorst, Christo
  - Lazzari, Gioele
  - Caffarri, Stefano
  date: 2022
  page-range: 1630-1648
  url: 
    value: https://onlinelibrary.wiley.com/doi/abs/10.1111/tpj.15643
    date: 2025-12-29
  serial-number:
    doi: https://doi.org/10.1111/tpj.15643
  abstract: SUMMARY The precise determination of photosynthetic pigment content in green organisms, chlorophylls (Chls) and carotenoids (Cars), is important to investigate many photosynthetic processes such as responses to environmental fluctuations or to gene mutations, as well as to interpret biochemical and structural results obtained on purified membranes and photosynthetic complexes. The most utilized methods for determination by spectrophotometry of Chl content in solution, usually 80% acetone, are based on the use of simultaneous equations. The advantages are the easiness and speed over chromatography, which also requires less common equipment. The disadvantage is that issues in sample preparation or in the measurement are not detectable, which could lead to wrong results. Here we propose a fast, accurate and (almost) error-proof method to measure Chl a, Chl b and also total Car content in a solution of pigments extracted from tissue, membranes or purified complexes. The method is based on the fit of the absorption spectrum of the acetone extract using the spectra of purified pigments as references. We show how this method allows a more precise and accurate estimation of pigment content as compared to classical equations, even in incorrectly prepared acetone solutions. Moreover, the method allows the discovery of artifacts in sample preparation or measurement and thus drastically reduces the risk of mistakes. Examples obtained on purified complexes are also discussed. Based on newly acquired Chl spectra, we also propose a new set of improved simultaneous equations that provide slightly different but more reliable results in comparison with the currently used equations.
  parent:
    type: periodical
    title: The Plant Journal
    issue: 6
    volume: 109
