# yaml-language-server: $schema=https://raw.githubusercontent.com/mkdjr/hayagriva/refs/heads/main/hayagriva.schema.json

wikipedia:
  type: web
  url: https://en.wikipedia.org/wiki/
  title: Wikipedia
  date: 2025-05-26

chlorophyll:
  type: web
  url: https://en.wikipedia.org/wiki/Chlorophyll
  title: Chlorophyll
  date: 2025-11-30







